# Generated by Django 3.1.1 on 2020-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_id',
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='articulos',
            field=models.TextField(),
        ),
    ]
