# Generated by Django 3.1.1 on 2020-09-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_auto_20200909_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.clientes'),
        ),
    ]
