# Generated by Django 3.1.1 on 2020-09-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_auto_20200911_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciones',
            name='articulos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion.articulos'),
        ),
    ]
